resolutionMode: highest
minimumReleaseAgeExclude:
  - "@dom-expressions/*"
  - "@solidjs/*"
  - babel-preset-solid
  - solid-js
  - vite-plugin-solid
  - filesystem-routing
patchedDependencies:
  vite-plugin-solid@3.0.0-next.16: patches/vite-plugin-solid@3.0.0-next.16.patch
